name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}          # e.g. culturahealth.ca
          username: ${{ secrets.SSH_USER }}      # deploy
          key: ${{ secrets.SSH_KEY }}            # your private key
          port: 22
          script_stop: true
          command_timeout: 20m
          script: |
            set -euxo pipefail
            cd /opt/cultura-ai
            git fetch --all
            git reset --hard origin/main

            # Use the app's virtualenv for dependencies
            /opt/cultura-ai/venv/bin/pip install --no-cache-dir -r requirements.txt

            # Restart the systemd service without prompting for password
            sudo -n /usr/bin/systemctl restart cultura
            sudo -n /usr/bin/systemctl status --no-pager cultura
